### ISSUE TITLE
Rom emulation bugs

### ISSUE THREAD

**Issue by benderscruffy** [drhelius/Gearboy#1]
Action Man - Search for Base X 
game over screen graphics are a bit messed up

4x4 World Trophy (Europe)
Runs really slow

Warriors of Might and Magic (USA) 
No input.

Defender Joust
Hangs when starting a Joust game.

Foreman for Real
Music is messed up, input not working in game.

Zerd no Densetsu
Crash.

Ken Griffey Jr.'s Slugfest (USA)
graphics are messed up during the game and there is a glitch near the ball on the menu screen

Feel free to add any game not working properly.

**Comment by drhelius** [comment]
Lego Alpha Team
No input.
Fixed

**Comment by benderscruffy01** [comment]
Barbie - Pet Rescue (Europe) (En,Fr,De,Es,It)
after you choose your language black screen with music playing

Road Rash (USA, Europe)
blank screen after the intro

007 - The World Is Not Enough (USA, Europe)
during gameplay there is a glitchy red line at the bottom of the HUD

**Comment by drhelius** [comment]
Thanks for the effort @benderscruffy!
