### ISSUE TITLE
Permission to add Gearboy to Steam as free DLC for RetroArch 

### ISSUE THREAD

**Issue by twinaphex** [drhelius/Gearboy#102]
Hi there,

we would like to seek your permission to include Gearboy as a core as free DLC for RetroArch on Steam.

The user would have to manually install this, it would be freely made available.

If there's anything you are unsure of or are hesitant about, don't hesitate to bring it to our attention. We will always go with whatever you decide.

**Comment by drhelius** [comment]
Thanks for your interest. No problem here, it's perfectly fine to include Gearboy as a free DLC for RetroArch on Steam.

**Comment by twinaphex** [comment]
Thank you! I will contact you when we are closer to release.
