### ISSUE TITLE
Unable to click menu bar and rendered only half during full screen mode

### ISSUE THREAD

**Issue by wnsgur4322** [drhelius/Gearboy#106]
When I set the full screen mode of the emulator, the user can't click menu bar and rendered only half of game.

**Comment by drhelius** [comment]
Fullscreen is broken in wayland, any help is welcome here.

But I think you're referring to other system, are you using Windows?

**Comment by wnsgur4322** [comment]
No, I was using Linux Ubuntu 18.04.
Actually, I solved the problem by fixing Qt source files!
Thank you !

**Comment by drhelius** [comment]
Thanks, I'll close the issue then.
