### ISSUE TITLE
keyboard input buttons A and B cant be remmaped

### ISSUE THREAD

**Issue by mrdeathjr28** [drhelius/Gearboy#108]
hi

keyboard input buttons A and B cant be remmaped

thanks for your work

**Comment by drhelius** [comment]
Thanks, just commited a fix.

**Comment by mrdeathjr28** [comment]
> Thanks, just commited a fix.

I try last build but error still remains, A and B buttons dont allow remaped

**Comment by drhelius** [comment]
Could you share some details of your system and setup? I can remap all keys in all platforms.

**Comment by mrdeathjr28** [comment]
> Could you share some details of your system and setup? I can remap all keys in all platforms.
> 
> And what do you mean with "don't allow"? Is the button not working, is the value not updating? Or is it not honoring the new value?

all other keys can be remaped in keyboard but when try remap A and B buttons remain same keys a and s

**Comment by drhelius** [comment]
Which new keys are you trying to assign ? CTRL, ALT or something like that?

**Comment by mrdeathjr28** [comment]
for example change for another keyboard keys case j, k , l or other

**Comment by drhelius** [comment]
I can't reproduce it. Are you using Windows?

**Comment by drhelius** [comment]
I think I found it.
Do you have more than one button mapped to the same key? In that situation I found that it fails to map the second key.

**Comment by mrdeathjr28** [comment]
Many thanks issue resolved

**Comment by drhelius** [comment]
Great. I'll fix that, thanks for reporting.
