### ISSUE TITLE
[MBC1] Mortal Kombat 1 & 2 stuck after game select

### ISSUE THREAD

**Issue by MediaMaquina** [drhelius/Gearboy#110]
Mortal Kombat I & II (USA, Europe).gb (55300d0a)
Stuck after selecting either game. Issue with multicart support i think.

**Comment by drhelius** [comment]
Thanks for reporting.

It's correctly being detected as MBC1M buy yet it fails. I'll have a look.

**Comment by MediaMaquina** [comment]
Super fast! I don't know if this is useful but there's info about that particular cart here:
http://forums.nesdev.com/viewtopic.php?f=20&t=14099&start=15

**Comment by drhelius** [comment]
I initially implemented this mapper some 8 years ago. I don't know when it broke.
But it's fixed now.
Thanks for reporting.
