### ISSUE TITLE
Doesn't save A and B buttons input setting

### ISSUE THREAD

**Issue by MediaMaquina** [drhelius/Gearboy#111]
It remembers all buttons mapping except A and B after restarting it.

**Comment by drhelius** [comment]
Are you referring to keyboard or Gamepad controls?

**Comment by drhelius** [comment]
Found it, thanks!

**Comment by MediaMaquina** [comment]
Thanks, it was keyboard sorry!

**Comment by drhelius** [comment]
Yes, it was a typo introduced in latest release, thanks for reporting!
