### ISSUE TITLE
Libretro build failure (WiiU - big endian codepath)

### ISSUE THREAD

**Issue by twinaphex** [drhelius/Gearboy#112]
Hi there,

I believe there is a typo in the code for big-endian targets -

https://github.com/drhelius/Gearboy/blob/master/src/GearboyCore.cpp#L328

Right now when this core is being compiled for WiiU, the following errors happen at compilation time -

http://paste.libretro.com/201922

**Comment by drhelius** [comment]
Thanks for reporting.
I don't own any big endian system so I will miss something ocassionally.
This should fix it.
