### ISSUE TITLE
Libretro buildbot failure - WiiU

### ISSUE THREAD

**Issue by twinaphex** [drhelius/Gearboy#113]
Hi there,

the WiiU build just broke -

http://paste.libretro.com/204259

/home/buildbot/tools/devkitpro/devkitPPC/bin/powerpc-eabi-g++ -DMINIZ_NO_TIME -DGEKKO -mcpu=750 -meabi -mhard-float -D__ppc__ -DMSB_FIRST -I/home/buildbot/tools/devkitpro/libogc/include -U__INT32_TYPE__ -U __UINT32_TYPE__ -D__INT32_TYPE__=int -DWIIU -DHW_RVL -O3 -Wall -D__LIBRETRO__    -c -o ../../src/Video.o ../../src/Video.cpp
/home/buildbot/tools/devkitpro/devkitPPC/bin/powerpc-eabi-g++ -DMINIZ_NO_TIME -DGEKKO -mcpu=750 -meabi -mhard-float -D__ppc__ -DMSB_FIRST -I/home/buildbot/tools/devkitpro/libogc/include -U__INT32_TYPE__ -U __UINT32_TYPE__ -D__INT32_TYPE__=int -DWIIU -DHW_RVL -O3 -Wall -D__LIBRETRO__    -c -o ../../src/Audio.o ../../src/Audio.cpp
../../src/Video.cpp: In member function 'void Video::SetColorPalette(bool, u8)':
../../src/Video.cpp:425:68: error: expected ')' before numeric constant
     *palette_color_final = ((color << 8) & 0xFF00) | ((color >> 8) 0x00FF);
                                                                    ^~~~~~
<builtin>: recipe for target '../../src/Video.o' failed
make: *** [../../src/Video.o] Error 1
make: *** Waiting for unfinished jobs....
COPY CMD: cp ./gearboy_libretro_wiiu.a /home/buildbot/buildbot/wiiu/dist/wiiu//gearboy_libretro_wiiu.a
cp: cannot stat './gearboy_libretro_wiiu.a': No such file or directory

From the looks of it, it's missing an 'AND', just like the last time.

WiiU is a big endian target and so BIG_ENDIAN is defined.

**Comment by drhelius** [comment]
Fixed.

Is there a way to get notifications directly from buildbot? I'd subscribe to them.

I have CI for most little endian platforms but I lack big endian.
