### ISSUE TITLE
Save file location on Windows

### ISSUE THREAD

**Issue by Kashouryo** [drhelius/Gearboy#117]
Hello! I can not find my save file alongside with my ROM files.
Where's the path for the config file and saves on Windows?

Thank you

**Comment by drhelius** [comment]
Save path defaults to "C:\Users\myuser\AppData\Roaming\Geardome\Gearboy\" on Windows.
You can use the rom path by selecting the option in "Emulator -> Save Files In ROM Folder" menu.
