### ISSUE TITLE
[libretro] SWorld crashes

### ISSUE THREAD

**Issue by keithbowes** [drhelius/Gearboy#118]
In the latest version of Gearboy, SWorld crashes.  I tried downgrading to 2.7.0 and it doesn't crash; it merely doesn't load the content.  I'm attaching the output of `retroarch --verbose` in case it will help track down what's wrong.

[log.txt](https://github.com/drhelius/Gearboy/files/4727065/log.txt)

**Comment by drhelius** [comment]
Thanks for reporting.
I tested SWorld in the desktop version with no issues so it may be a specific issue with RA.
I'll try to reproduce it.

**Comment by drhelius** [comment]
I can't get it to crash
![image](https://user-images.githubusercontent.com/863613/84070591-aed77600-a9cc-11ea-884e-7fafdf84646a.png)

**Comment by drhelius** [comment]
Can you share the SHA of the rom?
```
$ shasum sworld.gbc 
187470eb0a1bd2f57c161af2751044fd18635183  sworld.gbc
```

**Comment by drhelius** [comment]
Closing as non-issue

**Comment by keithbowes** [comment]
Yeah, I just tried to bisect it, but I couldn't find the revision that introduced the error and when I recheckedout (or re-checkout-ed?) 3.1.1 and compiled it, it worked fine.  Odd, as the new gearboy_libretro.so file is exactly the same size as the one in my cores directory, but it works, where the one in my cores directory crashes.  I can't imagine the reason, but it seems not to be a problem with Gearboy's code; I was just coming over to close this, but I notice that you beat me to it :).

**Comment by drhelius** [comment]
Sorry for the anticipation, I understood it wasn’t a problem in the code.

Thanks for reporting anyway, I really appreciate it.

**Comment by keithbowes** [comment]
Yeah, and I'm sorry for it taking me so long to get back.  I have anxiety and have seen that I have had new messages for months but was just too anxious to read them and just built myself up to do it today.
