### ISSUE TITLE
Clock too fast in Pokemon Crystal?

### ISSUE THREAD

**Issue by AnotherLife** [drhelius/Gearboy#122]
Using Retroarch on a modded Playstation Classic, I have a save of Pokemon Crystal that I was playing with Sameboy. Time wouldn't pass so I loaded the game with Gearboy. Now it seems minutes pass like seconds! Why is that?

**Comment by drhelius** [comment]
Thanks for reporting.

Can you share the save? It would be great to have both saves before and after saving with Gearboy.
