### ISSUE TITLE
Implement portable mode

### ISSUE THREAD

**Issue by ElektroStudios** [drhelius/Gearboy#127]
This is a (basic and must-have) feature request:

Please consider to implement portable mode, that is the **config.ini** and **imgui.ini** must be read/written in root directory of **Gearboy.exe**, and the battery files too (although I personally consider this a design inconvenience, I would prefer that the battery files be kept in the same folder from which I loaded the rom, like other common emulators does). 

One easy way for all users to set portable mode probably would be to let them create a "portable.txt" file in the root folder of **Gearboy.exe**, and then **Gearboy** should do the magic to recognise the installation as a portable mode. Or through an option in the emulator UI.

I cannot think of a good emulator that is not portable mode or does not provide the user a functionality to make it portable, like PCSX2, Dolphin, Citra, or VisualBoyAdvance-m to mention just some of them.

I'm in love with **Gearboy**'s UI and its functionality but this is a thing that stops me from using it as my main choice instead of others (such as **VisualBoyAdvance-m** because it has portable mode) because I need emulators to be portable, not to save settings in the user roaming folder like **Gearboy** does :(

Just please consider this feature request. Thanks in advance.

**Comment by drhelius** [comment]
Thanks for your comments.

You are right, this is something very easy to implement and could be very useful. I'll add it soon.

Regarding the battery files in the rom folder, this feature is already present in Gearboy. It can be toggle in the "Emulator" menu: "Save Files in ROM Folder". Maybe I should enable it by default.

**Comment by ElektroStudios** [comment]
Thanks a lot for taking the time to review and accept this feature request. About the battery files... sorry, my fault for not looking deep in the GUI menu.

While that option is configurable from the GUI and the setting will be stored in the .ini file, I think it does not matter at all what is the default behavior because can be changed easy. Probably other users prefer to save those files on appdata folder or on the emulator root folder.

That's all. Keep up the great work with Gearboy!

**Comment by drhelius** [comment]
Done! It will be available in the next release.

It can can be enabled by creating a `portable.ini` file.

**Comment by ElektroStudios** [comment]
Excuse me, just wondering if there are some kind of nighltly or dev. builds available to download?, I ask this to avoid the long waiting probably for moths until the next stable release can be published.

**Comment by drhelius** [comment]
Unfortunately I don't have a build system to publish nightly build but I do plan to implement Github Actions shortly.

I have been doing some performance improvements that I plan to realese shortly, in a few days, so a new release is on its way, sorry for the waiting.

**Comment by ElektroStudios** [comment]
Any E.T.A?
