### ISSUE TITLE
Go to address feature

### ISSUE THREAD

**Issue by BestPig** [drhelius/Gearboy#136]
Would be valuable to have a input to "go to address" in the disassembly view.
I tried to implement it without success.

* Bonus feature, double click on a jump or call to go to the destination address.

**Comment by drhelius** [comment]
Missed this, I'll add it to the list, thanks!

**Comment by oblivia-simplex** [comment]
I second this! I'm really enjoying the debugger, so far. Might be the best out there. But this feature would make a huge difference. (Instruction editing would be pretty cool too.)

**Comment by drhelius** [comment]
Thanks for your comments @oblivia-simplex, if you are using the debugger I will appreciate any more feedback about it you may have or any missing features you find

**Comment by drhelius** [comment]
go-to-adress implemented.

Double clicking may come later as I'm not storing enough informataion on each item in the dissasembler window.

Instruction editing is already possible by editing the opcodes in the memory window. Editing in the dissasembler view is far more complex to implement. I'm working in enabling the dissasembler to detect changes and disassemble again (it only does one pass right now).

**Comment by oblivia-simplex** [comment]
wonderful!

**Comment by drhelius** [comment]
Fixed, it will be integrated in master soon with other features
