### ISSUE TITLE
A couple of feature requests suitable for the future to come.

### ISSUE THREAD

**Issue by RokkumanX** [drhelius/Gearboy#139]
Hi and thanks for a wonderful emulator that is super easy to build and to use!!!

Instead of creating multiple feature request issues I thought of combining them into one.

**1.**
Adding the ability to use the Game Boy and Game Boy Color bios/boot roms at startup?
I have checked the 3.3.1 release which I built myself but couldn't find this ability in the emulator anywhere.

I know the SameBoy and Gambatte Libretro cores supports this feature and also the standalone version of bgb.

**2.**
Would it be possible to implement a setting for a "GBA" mode similar to the ones that SameBoy, Gambatte and bgb uses for games like Shantae, Oracle of Seasons and Oracle of Ages.

**3.**
This is the final request, which might be the easiest thing of these to implement.
It would be the ability to store and save more than one custom DMG/GB palette.

You could theoretically do that already by copying the values from the custom palette you have made in the GUI and store it in a text file and enter a new custom palette, but it would be tedious copying and pasting if you got quite a few of them.

Thank you very much you absolute legend and have an awesome day!

**Comment by drhelius** [comment]
Thank you very much for your comments and suggestions. My time is limited but I'll definitely add them to the list.

**Comment by vaguerant** [comment]
Suggestion 2, "GBA mode", is probably even easier to implement than the palette thing in suggestion 3. On a GBA, the `B` register is initialized to `01`, while on a GB/C, the register is initialized to `00`. There's no need to emulate any additional hardware or anything like that, it's just that one register change that triggers games to run in "GBA mode", which is really still just GBC mode.

The three games I'm aware of that use this, Shantae and the Oracle games, add some minor bonus content and also brighten the games' palettes to make them a bit easier to see on the terrifically dim original model Game Boy Advance screen. The color correction is minimally useful on an emulator, so this can make the games look a bit washed out, making "GBA mode" a bit of a compromise between the extra content and the inferior palette.

IIRC, there are patches on ROMHacking.net for all three games to unlock the extra GBA content without triggering the brightened palette, and personally I'd consider those patches to be much better than what you'd get from supporting "GBA mode" in the emulator, but most users probably don't want to go to that extra effort and would be willing to put up with the palette changes for the convenience of a menu toggle.

**Comment by drhelius** [comment]
Added GBA mode as it was really easy to implement.

**Comment by drhelius** [comment]
Added the possibility to customize 5 palettes for original Game Boy

**Comment by RokkumanX** [comment]
Thank you very much for all this and I also noticed you added the ability to toggle fullscreen, SOOOO awesome!

With future possibility of using the boot roms this might just be my no.1 GB/GBC emulator because damn it's that great!

**Comment by drhelius** [comment]
I'm working on boot roms, this was something that was already implemented and decided to remove. I'll give it another go.

**Comment by drhelius** [comment]
Done!

**Comment by RokkumanX** [comment]
@drhelius 

Whaaaaaaat, OMFG!!!
THANK YOU SO MUCH, this is AMAZING.

Aaaaaahhhhhhhhh I'm so happy right now.

**Comment by RokkumanX** [comment]
I just built GearBoy and it worked perfectly!

![working_2](https://user-images.githubusercontent.com/85066613/126527491-747853da-4bd2-4d93-92e5-670cc92b1ab7.png)

YOU ARE A GOD @drhelius
