### ISSUE TITLE
DMG color palettes look wrong on Wii U (big-endian issue?)

### ISSUE THREAD

**Issue by vaguerant** [drhelius/Gearboy#141]
I just tried out the libretro port on the Wii U, a console with a big-endian PPC CPU at its core. The Wii and PlayStation 3 also use big-endian CPUs, so this may occur on those and other BE platforms if that is the issue here. I haven't tested on any other (little-endian) devices for comparison, but I'm pretty sure the palettes are being interpreted incorrectly on Wii U.

**Original:**
![Tetris (World) (Rev A)-210710-185859](https://user-images.githubusercontent.com/5259025/125158043-afcf6e00-e1b1-11eb-9f4a-ba05a69fa998.png)
I would expect some kind of four-greens palette for Original, but get this red/blue look instead.

**B/W:**
![Tetris (World) (Rev A)-210710-190201](https://user-images.githubusercontent.com/5259025/125158046-b1009b00-e1b1-11eb-81fb-bfd460aca6e1.png)
I figured this would be four tones of gray, but this time it's a magenta and green affair.

As I say, I haven't tested on any other platforms, but I have a hard time believing this is expected behavior. I am running a current nightly (downloaded ~30 minutes ago), versioning information in RetroArch simply says Gearboy 3.3.1. I don't think I can get a specific commit number unless I'm missing that in the RetroArch GUI.

Game Boy Color games seem to be displaying correctly, I believe only palettization of DMG games is problematic.

**Comment by drhelius** [comment]
Thanks a lot for reporting. 

Yes, it looks like a big endian issue as I don't have a big endian platform to test.

I'll have a look at it later today, it would be very helpful if you could help me test the fix.

Also, could you test if Gearsystem core has color issues on WiiU? Both cores share code. 

Thanks again for your help.

**Comment by vaguerant** [comment]
I just tested a few Game Gear and Master System games on GearSystem and I couldn't see any palette issues at all. I did notice one minor unrelated thing which may be endian-based or just a general bug.

When launching the Master System game Choplifter (No-Intro: `Choplifter (USA, Europe).sms`) with Region set to "Auto", you get the Japanese "Sega Mark III" splash screen. Changing the Region to "Master System Export", you *still* get the Sega Mark III screen. However, if you change the Region to "Master System Japan", the game boots straight to the title screen, as it should on an *Export* machine. I will see if I can replicate this with other games and file an issue over there with any information I can find.

I don't have any kind of setup for building RetroArch Wii U cores, but if you're able to make test builds I'd be happy to try them out. Otherwise, I can try to get set up to make builds here, but I have family visiting the next couple of weeks so I won't have great time availability for a while.

No problem re: reporting and testing, glad to be of assistance.

**Comment by drhelius** [comment]
Thanks, you can grab latest builds for any platform that my cores support on the libretro CI repo: 

https://git.libretro.com/libretro/gearboy/-/jobs
https://git.libretro.com/libretro/gearsystem/-/jobs

I'll be telling you as soon as I pulbish a fix.

**Comment by vaguerant** [comment]
I can confirm the build off that `develop` commit completely resolves the issue on my end, all palettes working as expected!

**Comment by drhelius** [comment]
Thanks!! Working on the other issues now.
