### ISSUE TITLE
Custom folders [feature request]

### ISSUE THREAD

**Issue by RokkumanX** [drhelius/Gearboy#144]
Hi

First off, thank you again very much for everything.
Always a pleasure using this wonderful project!

I would like to ask if it would be possible to add the ability to choose custom save and savestate folders?

I really like having saves and savestates in separate folders, and most emulators have this ability present.

**Comment by drhelius** [comment]
Yes I'm looking into improving the savestates with screenshots and other info so this may fit.

**Comment by RokkumanX** [comment]
Thanks!

I have had the opportunity to mess with quite a lot of things in Visual Studio, changing themes, adding/removing palettes, changing shortcut keys, turning on/off settings, changing the application icon etc. etc.

I can basically make a tailor made Gearboy version with what's already there but unfortunately I can't/don't have the knowledge to add custom save and save state folders on my own which is pretty much the only thing left to make it final for me.

I'm really looking forward to have a standalone Game Boy/Game Boy Color emulator with all these candies after all these years relying on Libretro and it's cores.
