### ISSUE TITLE
Icon suggestion!

### ISSUE THREAD

**Issue by RokkumanX** [drhelius/Gearboy#145]
Hi

There doesn't seem to be an icon associated with Gearboy am I correct?

Here is a something I cooked up with PhotoShop.

![Gearboy  png](https://user-images.githubusercontent.com/85066613/126637801-b7b8d8b1-f2c0-47a1-b365-384c23b7cdcd.png)

This .zip file contains one bmp file (32x32) transparent and one ico file (32x32) transparent.

[Gearboy [icon].zip](https://github.com/drhelius/Gearboy/files/6862124/Gearboy.icon.zip)

It's a gear....and a boy...sort of.

Does the icon makes sense?

Feel free to use it if you like, just wanted to give something in return for everything you done!

**Comment by drhelius** [comment]
I never use Windows so I forgot about it.

I was working on a new icon with more resolution for the new iOS app so I may use that instead.

Thanks anyway!

**Comment by RokkumanX** [comment]
No problem, heck I might use it for myself and my own Windows builds.
Kinda looks cool, I have definetly seen worse.

**Comment by RokkumanX** [comment]
Looks pretty good here:

![done](https://user-images.githubusercontent.com/85066613/126672798-b23146e0-af44-4177-a524-fb3c9dbaa398.png)
