### ISSUE TITLE
Debugger setting breakpoints 

### ISSUE THREAD

**Issue by hami-sh** [drhelius/Gearboy#156]
Hello there! 
In version 3.4.0 I am trying to set breakpoints in your debugger. 
Low values for the PC seem to work just fine, however higher values (such as `C068`) are just added as `00:0000` whether clicked on or entered directly. 
Great program! Love the features but am trying to debug my own GB emulator and would love this to be fixed <3
All the best,
Hame

**Comment by drhelius** [comment]
Sorry for the late reply but it's now fixed

**Comment by hami-sh** [comment]
Great work! Thanks heaps for the help <3
