### ISSUE TITLE
Regarding the screen ghosting value

### ISSUE THREAD

**Issue by RokkumanX** [drhelius/Gearboy#159]
Hi!

This isn't an issue per se but the default value for the screen ghosting feature/setting is 0,50 in Gearboy and to tell the truth my eyes really hurts with a value this high for some reason, it feels really unnatural when a lot of things happens on the screen.

A lot of shaders I've seen usually use a value between 0,30 or 0,333 when it comes to LCD Response Time/Motion Blur.
Lowering the value from 0,50 to 0,30 helps a little bit for the eyes at least.

I don't have a working Game Boy at the moment to test if this kind of screen ghosting is present like the one in Gearboy with default value 0,50.

If I may ask, what is the 0,50 value based on?

**Comment by drhelius** [comment]
For the default value I compared the effect with the real hardware and some games that rely on blinking sprites to simulate transparency.

The ghosting in a real dmg is even more aggressive, but maybe less in gbc.

**Comment by RokkumanX** [comment]
Thanks for the explanation, maybe my eyes get hurt because the screen is bigger on a TV and the effect is more apparent then on a tiny Game Boy screen.

I have also noticed that it's different from game to game, Shantae for GBC is virtually unplayable for me with 0,50.
