### ISSUE TITLE
[macOS] version numbers broken in the latest release

### ISSUE THREAD

**Issue by core-code** [drhelius/Gearboy#177]
i've downloaded version **3.5** but when looking at it in the Finder (Get Info, Quick Look, Column View), it claims to be version **3.4**.

it seems you forgot to update the version numbers (`CFBundleVersion` and `CFBundleShortVersionString` entries in the `Info.plist` file)

<img width="262" alt="Screenshot 2024-03-04 at 17 11 14" src="https://github.com/drhelius/Gearboy/assets/1261954/af0ab289-5b86-47e5-a4ef-5672ffafcf02">
<img width="506" alt="Screenshot 2024-03-04 at 17 11 05" src="https://github.com/drhelius/Gearboy/assets/1261954/39305402-3f0f-4822-986a-a0ff0df65eaf">

NOTE: the very same issue applies to the latest gearsystem release ( https://github.com/drhelius/Gearsystem/releases/tag/3.5.0 )

**Comment by drhelius** [comment]
Thanks, you are right!

**Comment by drhelius** [comment]
Changed it so it updates automatically.
It will be fine in the next release.
Thanks for reporting!

**Comment by core-code** [comment]
awesome, thanks!
