### ISSUE TITLE
New to Debian. Just downloaded GearColeco but need help with controller

### ISSUE THREAD

**Issue by bwddppmm** [drhelius/Gearboy#178]
Hi got a game running on gearcoleco on Debian. Can play with keyboard but I can’t get it to work with my Xbox one controller, Atari vcs modern controller, or PlayStation 4 controller.

I am awful with Debian commands as I am
A windows guy and this is running Debian on my Atari VCS system
Pc mode

any help greatly appreciated!!!

**Comment by drhelius** [comment]
duplicated here: https://github.com/drhelius/Gearcoleco/issues/56
