### ISSUE TITLE
Architecture detection in About window

### ISSUE THREAD

**Issue by tordona** [drhelius/Gearboy#180]
Was testing the ARM64 build addition. Works great all around. Looks like the updated detection cascade catches multiple Windows architectures

![gearboy-about](https://github.com/drhelius/Gearboy/assets/1671976/8bc30f9f-c037-4488-8674-1aae6cc84369)

I think it should either use Windows specific predefined macros, `_M_X64` and `_M_IX86` or use an If Else for the Windows specific part.

**Comment by drhelius** [comment]
Thanks for reporting, I don't have an arm64 Windows so it's good to know 😅
