### ISSUE TITLE
converting .gearboy to .sav

### ISSUE THREAD

**Issue by pixelmoh** [drhelius/Gearboy#27]
I've been wanting to do this because I have been playing Pokemon Yellow edition on the gearboy, and now that I got the gba4ios app which also works with gbc games and gba games. I want to keep my save on the gearboy app but I want to put my save into the gba4ios app. So what do I do? also my ios device is non jailbroken.

**Comment by drhelius** [comment]
Just rename the files,they should be compatible. You will find the saves in the same folder your roms are placed. Check this: http://support.apple.com/kb/ht4094
