### ISSUE TITLE
Raspberry Pi + PiTFT screen

### ISSUE THREAD

**Issue by shenron** [drhelius/Gearboy#30]
Hi,
Gearboy run perfectly on my Raspberry pi. But ... I have a PiTFT screen and application start always on HDMI TV :(

**Comment by drhelius** [comment]
I don't think I can control that programmaticaly. I mean, if the Pi detect an HDMI connection it will disable the RCA output.

Look: https://www.raspberrypi.org/forums/viewtopic.php?f=35&t=88265

**Comment by shenron** [comment]
I can't test, I broke my binary gearboy ... :(

In my previous test I use Archlinux sdl2 lib
> sudo pacman -S sdl2

Now I want to build sdl2 with configure (I use Pi B rev 1 - 256ram)
> pacman -S freeimage openal pango libsndfile libjpeg libtiff libwebp automake 
> ../configure --disable-pulseaudio --disable-esd --disable-video-mir --disable-video-wayland --disable-video-x11 --disable-video-opengl

Build OK but when I launch a game :
> gearboy.bin: main.cpp:431: void init_ogl(): Assertion `surface != ((EGLSurface)0)' failed.

What's your opinion ?

**Comment by nicofossa** [comment]
I faced the same issue, but it's not a problem of raspberry itself.
You can force SDL to use your external monitor by
[code]
export SDL_FBDEV=/dev/fb1
[/code]
but there is an other problem: you will see a black window.
Looking at the source code included in "main.cpp" from the raspberry folder, it seems it uses hardware acceleration. Basically, the content of the windows is drawed using the GPU. As far as I know, the work of the GPU cannot be sent to a monitor linked with (for example) i2c, but only to HDMI or RCA (directly connected to GPU).
So, is there a way to disable hardware acceleration in raspberry build?

**Comment by drhelius** [comment]
You'll have to change the sources but this way will run slower. The Pi 2 may run that fine.
Let me check how this could be achieved and I can probably make the changes.

**Comment by nicofossa** [comment]
I've rewritten successfully the code so now it doesn't use native GPU acceleration but only SDL acceleration. Now the problem is how to disable hardware acceleration and force sdl to use /dev/fb1 as main monitor

**Comment by drhelius** [comment]
That was fast! 
If you're using sdl this should be helpful:

https://wiki.libsdl.org/SDL_CreateRenderer

**Comment by drhelius** [comment]
Set this two also:

```
SDL_putenv("SDL_FBDEV=/dev/fb1");
SDL_putenv("SDL_VIDEODRIVER =fbcon");
```

**Comment by nicofossa** [comment]
Already tried these option, does not work. Moreover SDL_putenv is deprecated.
I compiled succesfully a version that blit "theScreenBuffer" directly on the screen (directly is non really correct, because I have to convert the pixels to the right format used by the screen). This is a very resource-eater operation, I can't find a solution to optimize it... By the way, with a rudimental frameskip 1/10 and no audio it is quite playable (I'm testing the emulator with pokemon yellow)
If you want, I can share my work with you; maybe togheter we can find a solution

**Comment by inktrebuchet** [comment]
I have been messing with my pitft display for a bit now, trying to figure this out. I came across this page which has got gearboy working on the pitft display. 

Surprisingly, I still can't quite figure out how to resize the emulator to fit the screen... I must be overlooking something simple.

**Comment by drhelius** [comment]
Now that you can use Gearboy through RetroArch this shouldn't be an issue.
