### ISSUE TITLE
Arrow key problem

### ISSUE THREAD

**Issue by JoelSjogren** [drhelius/Gearboy#34]
When I hold down an arrow key to walk (in Pokemon Silver) there seems to be a bug caused by automatic key repetition made by the operating system: I don't walk continuously but stop every step or the other.

This can be worked around by using letter keys like ijkl instead.

**Comment by drhelius** [comment]
Can you test it with other game? That particular game uses tiles for the character to walk, so the character will always stop aligned with the game tiles.

**Comment by JoelSjogren** [comment]
Which one should I try?

**Comment by drhelius** [comment]
Supe Mario Land will do, any with smooth controls...

**Comment by JoelSjogren** [comment]
Same problem. But I notice that the problem goes away momentarily if I press and hold an arrow key followed by another key (like A on the keyboard). Here's a video: https://drive.google.com/file/d/0BwVv1Z9Tmq_yWjhmQy1Dbmt1OUk/view?usp=sharing (bug at 0:15--0:20).
