### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by dannye** [drhelius/Gearboy#35]
Hi.
I am used to using bgb on Windows for its powerful debugger, and I was looking for a good Mac alternative so I was excited when I came across this.

I cloned the repo and used `brew install homebrew/games/gearboy` and then `brew linkapps gearboy`

Here is the output:
http://pastebin.com/59wLSBry

When I launch Gearboy.app it seems to open fine, but when I Game Boy->Load ROM... the game window remains black.

And when I click the red circle to close the window, the app seems to freeze.

Any suggestions as to what might be the problem?

I am on Mac OS X 10.11.1

**Comment by drhelius** [comment]
Looks like a problem with the rom, can you share it?

**Comment by dannye** [comment]
I tested with many different roms, Pokemon Red, Yellow, Crystal, TCG.

**Comment by drhelius** [comment]
By using brew you are getting all the dependencies. It's working for me within several macs. 

Are you using compressed roms? 

Let me prepare a  binary 
download for you to test.

**Comment by dannye** [comment]
No, I am using normal .gb and .gbc files.

**Comment by dannye** [comment]
Do you have the free time today to share a binary?

**Comment by drhelius** [comment]
This is the app resulting of running `brew install homebrew/games/gearboy`

https://www.dropbox.com/sh/m78nvkt1qcphqol/AABgNvTmOKSVY3vJJf-90F4da?dl=0

**Comment by dannye** [comment]
Yeah, that app is running fine, with the same roms. The app I built is 518kb and the one you just shared is 522kb.

Do you want me to send you mine?

**Comment by drhelius** [comment]
That's pretty weird. If you share it with me I may have a look.

The debug ui is not implemented yet, there's a disassembler internally but not ui at the momment. Not hard to do anyway.

**Comment by dannye** [comment]
The debugger was the cause of most of my excitement. I have not found any emulator for the Mac with a debugger like bgb's.

Also, I notice this does not emulate SGB features. Is that a possible future update?

Here is the .app

**Comment by drhelius** [comment]
Oops, sorry about that, the emulator is far from finished.

Yep, those are possible features, any help is welcome :) Anyway I'm currently (and slowly) working on a NES one.

I checked your app but I don't have a clue why are you getting a different one.

**Comment by drhelius** [comment]
Found the issue with the black screen when installing from brew.
I just issued a pull request so it should be fixed sooner than later.
