### ISSUE TITLE
Pokemon Maize crashing Gameyob

### ISSUE THREAD

**Issue by Ziko577** [drhelius/Gearboy#37]
I tried to play this game in SGB mode as the game is programmed to natively, and it crashes on loading to the title screen. The emulator crashes as a result and even disabling the SGB mode still gives an issue after I closed the rom. It has to have something to do with how it's made somehow but the creator of the hack says this isn't the case at all.

**Comment by drhelius** [comment]
Can you share the rom?

**Comment by Ziko577** [comment]
http://www.mediafire.com/download/h7b77re9let07fz/Pokemon_Maize.zip
It's the latest beta patch at 3.2 as of this time.

**Comment by drhelius** [comment]
It's is running pretty well for me, maybe you are not using the latest version?

**Comment by Ziko577** [comment]
Oh crap. I just realized this is the iOS emulator and not the DS one repository. I'm sorry about that. I will move this to the proper place. Consider this closed now.
