### ISSUE TITLE
CPU usage under Windows 10

### ISSUE THREAD

**Issue by CidVonHighwind** [drhelius/Gearboy#40]
While playing a game the emulator uses <= 1% of my CPU. When I do other stuff while the emulator is still open the CPU usage goes up to 15%. Probably not a big problem for most of the peope but it seems strange.

**Comment by drhelius** [comment]
Thanks for reporting. 
Which OS are you using?

**Comment by drhelius** [comment]
Doh! 
Sorry I just saw the title :)

**Comment by drhelius** [comment]
Fixed!
Better late than never...
