### ISSUE TITLE
Minor patches aimed at Fedora packaging

### ISSUE THREAD

**Issue by dmoerner** [drhelius/Gearboy#41]
Hi,

Thanks for writing Gearboy, it's a great emulator. I'm looking into packaging it for inclusion in Fedora. To package it, I've been applying a number of small patches that I wanted to share with you. Here's a draft of the package, if you're curious: https://copr.fedorainfracloud.org/coprs/dmoerner/Gearboy/

I welcome you to apply these patches if you'd like. All the patches are in the master branch of my forked repo (https://github.com/dmoerner/Gearboy), but I also include here links and extra descriptions.

1. Build against system miniz: Fedora, like most Linux distributions, prefers to build against system copies of libraries. The patch is trivial: https://github.com/dmoerner/Gearboy/commit/c802ea9e8e85456826440530c8e22fc789c49900

2. Man page: I wrote a very simple man page. I included the note about using alsa to fix the sound: https://github.com/dmoerner/Gearboy/commit/7c12d85f83ad8f5f3854cabc42d79320f3957a14

3. Fedora requires desktop files for GUI applications and recommends appdata.xml files. I wrote basic versions of each: 
https://github.com/dmoerner/Gearboy/commit/d7b9d2eeca6edd880a154936816e14e6c1fe6c77
https://github.com/dmoerner/Gearboy/commit/993bb7266968407a82760f9cc87447347e2791fc

4. Fedora includes extra -debuginfo packages. For these to work properly, it is preferred that some minor stylistic considerations be cleared up. I switched to UNIX-style file endings in two files, and removed the executable bit on 8 files: https://github.com/dmoerner/Gearboy/commit/b661a2dceb94f12b14873cc51f6b6a6e7bb1c83d

I totally understand that you might not want to include all these patches upstream. But #4 should be pretty trivial, and the man/desktop/appdata files could just be dropped in platforms/linux/Gearboy.

Daniel

PS: I'm not sure if you're aware, but the audio issue on Linux can be fixed by forcing SDL to use alsa: https://wiki.libsdl.org/SDL_AudioInit.

**Comment by dmoerner** [comment]
Hi, I have a follow-up question: Is it necessary to link against SDL2main in addition to SDL2? On Fedora, this pulls in SDL2-static as a build requirement. However, no header from SDL2-static is included in the build. Building without linking to SDL2main seems to work fine with my tests. An automated build-requirement tester on Fedora, auto-buildrequires, also seems to confirm that SDL2main is not required.

**Comment by drhelius** [comment]
Whoa! Amazing work, of course I'm merging it.

1. Is nice but unfortunately this will break Windows and iOS builds without an easy fix, not right now.
2. OK
3. OK
4. OK

Can all this new files be put on the "platforms/linux/Gearboy" folder?

About linking "SDL2main", yes you're right, just removed it. I fixed the ALSA problem too. 

Can you make a pull request with 2, 3 and 4?

It would be amazing if you could also modify the README.MD to include the building instructions of Gearboy on Fedora, dependencies needed and the like.

Thanks!

**Comment by dmoerner** [comment]
Thanks for the quick comment! Definitely understand about the miniz situation. And great to hear about SDL2main and about the ALSA fix! It works for me.

I made a pull request with 2, 3, and 4, and included an update to README.md. https://github.com/drhelius/Gearboy/pull/42

**Comment by drhelius** [comment]
Merged!

**Comment by dmoerner** [comment]
Great, thank you so much! 

I was wondering when you thought you might tag a new release, even a point release (2.3.1). I'd love to be able to include these changes directly from upstream.

**Comment by drhelius** [comment]
Done!
