### ISSUE TITLE
Clarify status of src/boot_roms.h

### ISSUE THREAD

**Issue by dmoerner** [drhelius/Gearboy#43]
Hi,

src/boot_roms.h has the appropriate GPLv3+ license header. But it mainly contains a series of bytes with the comment "// From GameBoy-Online emulator". But I was wondering if you could follow up with more information about the contents of this file and where it came from.

Thanks

**Comment by drhelius** [comment]
They came from the GameBoy-Online emulator (https://github.com/taisel/GameBoy-Online/) but it looks like it has been pulled out since I copied them back in 2013:
https://github.com/taisel/GameBoy-Online/blob/master/js/GameBoyCore.js#L270

So the reference is no longer valid then.

**Comment by dmoerner** [comment]
Thanks for the information. Here's a bit more history, in case you're curious: http://gbdev.gg8.se/wiki/articles/Gameboy_Bootstrap_ROM

(The upshot of this is just that Gearboy will be packaged in rpmfusion instead of Fedora.)

**Comment by drhelius** [comment]
Just removed the comment.

It is possible to easily remove the roms for a Fedora version.
