### ISSUE TITLE
Enable Saves to Network folder: 

### ISSUE THREAD

**Issue by ddavisgraphics** [drhelius/Gearboy#44]
On iOS devices it would be nice to allow save files to go dropbox, googledrive, or other networked folders so that if apple shuts down the app you can quick pickup where your game dropped off.

**Comment by ddavisgraphics** [comment]
I'm looking at how to do it ,but not sure off the top of my head. Possible enhancement.

**Comment by ddavisgraphics** [comment]
-- I just re-installed after apple shut the app down, it now runs again and all the saves are there.

**Comment by drhelius** [comment]
You can backup your saves by using [iTunes file sharing](http://support.apple.com/kb/ht4094) and copying the .gearboy files to your drive.
These saves can be used in other emulators too.
