### ISSUE TITLE
A strange big use of CPU when no game is loaded

### ISSUE THREAD

**Issue by RyDroid** [drhelius/Gearboy#46]
Hi.

When I launch Gearboy, even when no game were loaded, it uses at least 30% of a CPU!

- OS: Trisquel GNU/Linux 7 (based on Ubuntu 14.04)
- CPU: Intel(R) Core(TM)2 Duo CPU  P8600  @ 2.40GHz (`cat /proc/cpuinfo | grep 'model name' | uniq`)

![Screenshot](https://framapic.org/RFKDbCsd1bzk/bBuiV8U18Rkv.png)

Regards.

**Comment by drhelius** [comment]
Thanks for reporting

**Comment by RyDroid** [comment]
Thanks for this free/libre emulator.

**Comment by drhelius** [comment]
Fixed!

**Comment by RyDroid** [comment]
Thanks!
