### ISSUE TITLE
Windows release missing Qt platform plugin

### ISSUE THREAD

**Issue by bparker06** [drhelius/Gearboy#54]
![img](https://i.imgur.com/VAcwMSs.png)

**Comment by hyarsan** [comment]
Oh my, I thought that I was the only one who gets that message!

**Comment by TylerCode** [comment]
Can confirm on Windows 10 Pro x64 that I'm getting the message with the build

**Comment by LMLB** [comment]
Same

**Comment by woutput** [comment]
I see the same message (cmd > ver: "Microsoft Windows [Version 10.0.17134.407]")
Is there a containment or solution?

**Comment by drhelius** [comment]
Could you please test this new release?

https://github.com/drhelius/Gearboy/releases/download/gearboy-2.7.0/Gearboy-2.7.0-Windows.zip

**Comment by woutput** [comment]
Works, thanks!
