### ISSUE TITLE
Toolbar all black until clicked and other problems

### ISSUE THREAD

**Issue by dannye** [drhelius/Gearboy#55]
I built the source on Linux using the same commands listed in the readme
The toolbar appears as a black stripe, however the buttons are still click-able
It's also spamming the terminal with this warning:
![image](https://user-images.githubusercontent.com/5231310/34197872-e95c95f0-e52d-11e7-897e-9aa0065d11ce.png)

It's also using 100% CPU power (even while paused):
![image](https://user-images.githubusercontent.com/5231310/34198247-47975e92-e52f-11e7-9ac1-0d9b5750d4cb.png)
(that shows before and after killing Gearboy)

**Comment by orbea** [comment]
I can reproduce the QOpenGLContext messages, but the toolbar is fine here. That said I use a gtk2 theme with qt5 (Something gtk3 can't do...) so that might make a difference.

**Comment by orbea** [comment]
Here are some links that may help.

https://stackoverflow.com/questions/24894635/qt-managing-opengl-context-in-a-separate-thread
https://stackoverflow.com/questions/32140590/qt-opengl-drawing-into-non-exposed-windows

**Comment by drhelius** [comment]
I fixed the cpu problem when idle.
I can't reproduce the menu bar issue nor the swapBuffers message in Fedora/Gnome but I made some modifications that may help with both issues.

**Comment by orbea** [comment]
I can no longer reproduce the `QOpenGLContext` message, thanks! However I was never able to reproduce the other issue.

**Comment by dannye** [comment]
The cpu usage problem and the QOpenGLContext message is gone, but the tool bar is still black for me.
Like it said, it's still functional so it isn't really that big of a problem. Thanks for you help!

**Comment by drhelius** [comment]
Thanks for testing!
