### ISSUE TITLE
How can I get a save file from another emulator onto gearboy on my iphone?

### ISSUE THREAD

**Issue by mddrill** [drhelius/Gearboy#58]
Do you know if there's some way to do this? Would I have to include it in the assets of the xcode project somehow?

**Comment by drhelius** [comment]
Right now you can rename the save file to name_of_rom.gb.gearboy and upload it to your iPhone with [iTunes file shares](http://support.apple.com/kb/ht4094) and put it in the same folder of the rom file.
I'm working on the save code so you won't need to rename them.

**Comment by mddrill** [comment]
I did this and now the app stopped working. When I open it, it immediately closes. Any ideas?

**Comment by mddrill** [comment]
Oh, nevermind. I reinstalled the app and retried this and it worked.
