### ISSUE TITLE
File paths

### ISSUE THREAD

**Issue by orbea** [drhelius/Gearboy#59]
Hi,

Is it possible that Gearboy could be made to not create `gearboy.ini` and `game.gb.gearboy` in the current directory?

With the Qt version on linux it should use a path like `~/.config/gearboy/` or `~/.local/share/gearboy/`. I am not sure which is preferable?

For the libetro core it should respect the `System/Bios` directory for `gearboy.ini` and the `Save directory` for `game.gb.gearboy`. In RetroArch these directories default to the content directory but the use can change them to whatever they want.

**Comment by drhelius** [comment]
Sure, I'm already working on it.

**Comment by orbea** [comment]
Awesome, its much appreciated!

**Comment by drhelius** [comment]
Fixed.

In addition, I've included a new option in the Qt version that let you choose if you want your save files in the same directory of the rom file or not, in that case they go to `~/.local/share/gearboy/`

**Comment by orbea** [comment]
I just noticed your reply now, thanks a lot! It seems to be working fine here. :)

**Comment by orbea** [comment]
@drhelius I just wanted to let you know that a slackbuild for Gearboy including both the qt5 frontend and libretro core has been made for slackbuilds.org and is currently in their 'ready' queue waiting for the next merge. For now it uses a tarball I created myself for the current master, but in the future I would prefer to follow your stable releases and will switch to that when you are comfortable with tagging another stable release. :)

**Comment by drhelius** [comment]
That's very nice, thanks! A new release tag is almost there.
