### ISSUE TITLE
Save file corrupted after swiping right

### ISSUE THREAD

**Issue by mddrill** [drhelius/Gearboy#60]
I was using the ios version and, in the middle of a game, swiped right to get to the tableview of games. Now the save file is corrupted. The game doesn't have the "Continue" option, only "New game". I know it's the save file because it doesn't work in other emulators either. Have you seen this behavior before? Any idea what's causing it? A quick fix may be to just make it so that you cant swipe right to get to the tableview controller, but I can't figure out how to do that.

**Comment by drhelius** [comment]
Switching to the list view while playing a game will trigger a SRAM save to file, that's the normal behavior, so your save is ready in case you choose a different game.
Does it keep happening to you?
Does it happen only when you swipe or pressing the "Games" button on the top left corner too?

**Comment by mddrill** [comment]
I can't seem to reproduce it now. I thought I had tried to reproduce it a few times before logging this, but I guess I forgot.

I had pressed the "games" button on the top left several times before this issue and nothing happened. So, when it does happen, it seems to only be from a swipe. But again, I can't reproduce it. I'll let you know if I see it again.
