### ISSUE TITLE
Enable 32 and 64-bit builds for Raspbery Pi 3

### ISSUE THREAD

**Issue by AntonioND** [drhelius/Gearboy#68]
As far as I can see, the current Makefile only builds the RPi3 binary for 64-bit OSes. This wouldn't work in a 32-bit OS.

In my RPi3, the target architecture for 32 bit is called armv7l. It should be possible to compile this emulator for both architectures. It could be a build option that defaults to 64 bit so that the code keeps working the same way it is working right now. Another option would be to detect it with a command.

**Comment by AntonioND** [comment]
Maybe `-march=native` would be the best option, but that would make it impossible to cross compile it.

https://gcc.gnu.org/onlinedocs/gcc/ARM-Options.html
https://gcc.gnu.org/onlinedocs/gcc/AArch64-Options.html

**Comment by drhelius** [comment]
I'd rather prefer creating new folders for rpi32

**Comment by drhelius** [comment]
Could you provide an example make file for 32 bits?

**Comment by AntonioND** [comment]
Sure, I'll do it tonight.

**Comment by AntonioND** [comment]
I'm not sure about the folders, that's more an organizational decision that you have to take, so feel free to reorganize that or to do it your own way...
