### ISSUE TITLE
QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined

### ISSUE THREAD

**Issue by orbea** [drhelius/Gearboy#70]
When opening the qt5 Gearboy frontend this is printed several times. The only possible symptom I see is that Gearboy's window does not scale well in the tiling wm I am using (Spectrwm). I'm not sure the full implications of this, but thought it would be good to point out.
```
$ Gearboy 
qt5ct: using qt5ct plugin
qt5ct: D-Bus global menu: no
QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined
QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined
QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined
QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined
QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined
QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined
QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined
QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined
QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined
QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined
QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined
QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined
QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined
QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined
QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined
QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined
QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined
QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined
QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined
QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined
QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined
```

**Comment by orbea** [comment]
Also...

OS: `Slackware64-current`
`Gearboy-2018.03.26_81bb716_master-x86_64-1_git`
`SDL2-2.0.8-x86_64-1`
`qt5-5.7.1-x86_64-1_SBo`

**Comment by orbea** [comment]
I tried to bisect this, but due to unrelated build failures the bisect failed.
```
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
c658cb12a7ac80f9965ab6d7a5252880a8b4fc5d
da2f742ed73ca74533853cca4dab75188b2c2fdd
fe833a5ccd934808f15930bfeb864113e9cb5236
bfa2576efc5d7507f235fa982418af7fa53b60cf
cffabab1392954170a5f8ff64aecede0b468cb92
8f73142516d0a3dfe29bd25823e0349a57f74001
We cannot bisect more!
```
c658cb12a7ac80f9965ab6d7a5252880a8b4fc5d
da2f742ed73ca74533853cca4dab75188b2c2fdd
fe833a5ccd934808f15930bfeb864113e9cb5236
bfa2576efc5d7507f235fa982418af7fa53b60cf
cffabab1392954170a5f8ff64aecede0b468cb92
8f73142516d0a3dfe29bd25823e0349a57f74001

**Comment by drhelius** [comment]
Check this issue: https://github.com/drhelius/Gearboy/issues/55

I tried to solve the swapBuffers() problem in the past, I'll have to investigate it further.

Is this something that worked before those commits?

**Comment by orbea** [comment]
Yea, the 'QOpenGLContext' were gone for a while and then came back in one of the above commits.

**Comment by orbea** [comment]
Also I noticed now that Gearsystem is also affected.

**Comment by drhelius** [comment]
I checked all those commits and I can't uderstand why it is happening again.
I can't reproduce it on Fedora 27.

**Comment by orbea** [comment]
I suppose it could be specific to certain Qt5 versions. I have qt-5.7.1 installed now. I can check newer versions if required.

**Comment by orbea** [comment]
@drhelius Can you reproduce it if you start Gearboy or Gearystem like...

1. Go to any empty tty.
2. `xinit /usr/bin/xterm -- :1`
3. In the new x session with just xterm start Gearboy.
4. It doesn't seem to occur every time and may need to be closed and started again.

**Comment by drhelius** [comment]
Fixed!

No more Qt for me :sweat_smile:

**Comment by orbea** [comment]
Its now SDL2 only? :)

**Comment by drhelius** [comment]
SDL2 + ImGUI
