### ISSUE TITLE
Add quit option to menu

### ISSUE THREAD

**Issue by orbea** [drhelius/Gearboy#71]
Would it be possible to add a `quit` option in the `Game Boy` menu, perhaps below `Load State`? My tiling window manager does not offer any window decorations so the only way I have to close Gearboy is the `esc` keybind and force killing it.

**Comment by drhelius** [comment]
Yes, you can count on it.

**Comment by orbea** [comment]
Cheers. :)

**Comment by drhelius** [comment]
Done!

**Comment by orbea** [comment]
It works here, thanks!
