### ISSUE TITLE
Disable swipe to get from detail to master view controller on ios version

### ISSUE THREAD

**Issue by mddrill** [drhelius/Gearboy#75]
This is driving me nuts. I'm trying to edit my forked version so that when you swipe left, it doesn't exit the detail viewcontroller to go into the master viewcontroller. I think this is the default behavior for detail-master on small devices, but it's problematic in this specific app, as I keep accidentally exiting the game by swiping out of the detail when turn left or right on the keypad.

From my googling, it seems that I should be able to fix this easily by adding `splitViewController.presentsWithGesture = NO;` to the `application:didFinishLaunchingWithOptions:` method in the app delegate, but that doesn't seem to be working.

Have you tried adding the feature before? Do you have any idea how I could about doing it? I'm wondering if there's something usual in this app that would prevent such a solution from working.

**Comment by mddrill** [comment]
Got it https://stackoverflow.com/questions/49968978/how-to-disable-swipe-back-gesture-with-master-detail-view-in-ios-11

**Comment by drhelius** [comment]
Sorry, i didn't have the time to check this out.

It could be a nice feature to have so I will reopen the issue so I don't forget about it.

Also, if you like to contribute it with a PR that would be really appreciated.

**Comment by mddrill** [comment]
I closed it because I figured it out already. I can contribute a PR if you tell me how, I’ve made a couple changes including this and adding a feature to airdrop roms and save files to and from the app.

**Comment by mddrill** [comment]
Do you want me to push to the develop branch and then create a PR to merge that to master?

**Comment by drhelius** [comment]
You can create a new branch in your repo with your changes or leave them in master, then make a PR from this branch to my develop branch.
When you do that there is a checkbox that allow me to make changes before merging, so I can help you integrate your changes.

**Comment by mddrill** [comment]
I think I need permissions

> remote: Permission to drhelius/Gearboy.git denied to mddrill.
> fatal: unable to access 'https://github.com/drhelius/Gearboy.git/': The requested URL returned error: 403

**Comment by drhelius** [comment]
You don't need permission to create a PR.
I see you have all your changes in your master branch, that's ok.
Go here: https://github.com/drhelius/Gearboy/pull/new/develop
On the right select your master branch in your repo, on the left select my develop branch in my repo, then click create pull request, then there is a checkbox that allow me to make changes before merging.

**Comment by mddrill** [comment]
By the way, I noticed that this runs slower than another emulator that I run on my Mac. Is this due to limitations of the iphone vs my Mac? Or do you think there's some way to speed it up through code changes?

**Comment by mddrill** [comment]
Now the app is crashing whenever I open it. Probably as part of that same issue.

When I look at the console logs I get 

> Failed to start job with error <NSError: 0x10078bc50; domain: NSPOSIXErrorDomain; code: 3; reason: "No such process"> {
>     description = "Unable to get pid for label UIKitApplication:com.matthewdrill.Gearboy[0xb5d8][66]";
>     failureReason = "No such process";
>     userInfo = {
>         BKLaunchdJobLabel = UIKitApplication:com.matthewdrill.Gearboy[0xb5d8][66];
>         BKLaunchdOperation = launch_get_running_pid_4SB;
>     }
> }

This has been happening since I first built this project on my iphone. It works at first but after open the app several times it starts to crash until I re-install it with xcode.
