### ISSUE TITLE
(Libretro) (Wii U) Save States Won't Load

### ISSUE THREAD

**Issue by dagreatbuzzsaw** [drhelius/Gearboy#80]
Hello!
Save States fail to load on the Wii U Port of Libretro's Gearboy core.

**Comment by drhelius** [comment]
Thanks for reporting.
Unfortunately I don’t have a Wii U to test so this may take some time until I figure out what’s going on.

**Comment by AnotherLife** [comment]
They don't work on the PS Classic either.
