### ISSUE TITLE
Black screen on Arch Linux

### ISSUE THREAD

**Issue by mvrozanti** [drhelius/Gearboy#86]
Hi there

I got no errors but it opens a black window when following the installation instructions from README. Not sure how to proceed

`Linux 4.18.16-arch1-1-ARCH #1 SMP PREEMPT x86_64 GNU/Linux` 

I installed the `glew` version 2.1.0-1, `glew1.10` and `lib32-glew`

**Comment by drhelius** [comment]
Sorry for the late reply, did you manage to get it working?

Which desktop are you using?

Note that the emulator needs a hardware device for OpenGL to work, but I'm more inclined towards a GTK/Qt issue.

**Comment by mvrozanti** [comment]
No problem!
I had no GPU at the time, so no bug here
Thanks for the awesome project!
