### ISSUE TITLE
Game running too fast

### ISSUE THREAD

**Issue by saeschdivara** [drhelius/Gearboy#88]
Hi on my MacOS Mojave with Qt 5.12 the emulation of Pokemon Crystal is super fast, make 3 times as fast as it should be. Is this a bug?

**Comment by drhelius** [comment]
Is this happening with more roms?
Do you know your current monitor refresh rate?

**Comment by saeschdivara** [comment]
Yes, with every one of them.
Honestly I am not sure (I haven't found out where to find this information (maybe this is correct: https://www.apple.com/us_smb_78313/shop/question/answers/product/HKMY2VC/A/refresh-rate-with-a-2016-12-inch-macbook/Q4JCCJYAJDCJ9PT7X)
Probably 48hz

**Comment by drhelius** [comment]
Hi, is this still a problem? I'm not able to reproduce it.

**Comment by drhelius** [comment]
Yes, got it. Disabling sound with Qt 5.12 definitely makes the emulator run too fast.

**Comment by siiv-project** [comment]
Thank you for fixing this :)
