### ISSUE TITLE
How Gearboy emulate time

### ISSUE THREAD

**Issue by Sagigamil** [drhelius/Gearboy#92]
Hi,

I'm tring to run Gearboy on esp32 controller,
So far, it works but with a small issue: only 8fps, and I think that
the problem is the way that the Gearboy count time.

Please explaine to me how the Gearboy mesure time, maybe it uses not-initialized periph or not fit function in the esp32.

Thank you,
sagi

**Comment by drhelius** [comment]
You are expected to call GearBoyCore::RunToVBlank and present it’s results every 16ms, thus producing a frame rate of 60 fps. Real Game Boy runs at 59.7 fps but you can ignore that.

https://github.com/drhelius/Gearboy/blob/master/src/GearboyCore.h#L47

This method will give you a full rendered frame buffer you have to present on the screen at the same frame rate (every 16ms). At the same time it’ll give you the sound samples you’ll have to send to your audio device. The total sample count is provided as a return parameter.

If the target platform doesn’t have enough power, a single call to GearBoyCore::RunToVBlank may take longer than 16ms. If this happens you won’t be able to maintain 60fps and you may have to drop frames or whatever...

**Comment by Sagigamil** [comment]
The esp32 runs at 260Mhz, and this is run slow even if I pass the screen image update.
I do not understand how the Gearboy know what is the time in milliseconds, since the RunToVBlank  function calls in infinite loop without sleeps in the other platforms, so how this is works? I think that I'm missing something

**Comment by drhelius** [comment]
Gearboy doesn’t know anything about the external loop time. It just emulates one frame, no matter how many times per second you call it, you have to take care of the time yourself.

There are sleeps in some platforms (https://github.com/drhelius/Gearboy/blob/master/platforms/qt-shared/RenderThread.cpp#L121) and some tricks like Vsync (https://github.com/drhelius/Gearboy/blob/master/platforms/ios/Gearboy/MasterViewController.mm#L39) and audio sync (https://github.com/drhelius/Gearboy/blob/master/platforms/audio-shared/Sound_Queue.cpp#L141) in others, to avoid running faster than 60fps.

**Comment by drhelius** [comment]
The easiest platform to follow is Raspberry Pi (https://github.com/drhelius/Gearboy/blob/master/platforms/raspberrypi/main.cpp).

But probably the esp32 @ 240Mhz doesn’t have enough power for Gearboy :(
