### ISSUE TITLE
Possible broken link on "About" screen

### ISSUE THREAD

**Issue by sdunc** [drhelius/Gearboy#98]
I just installed gearboy on macosx (brew install gearboy)

From the top bar: **Gearboy** -> **About gearboy**

Shows the following screen:

<img width="753" alt="Screen Shot 2019-12-28 at 11 38 35 AM" src="https://user-images.githubusercontent.com/19787449/71546609-c8c55500-2966-11ea-91bd-8649f840924a.png">

The link to authors website is a NSFW Japanese website. 
Is this purposeful or a mistake?

**Comment by sdunc** [comment]
NSFW:
http://www.ignaciosanchezgines.com/

**Comment by drhelius** [comment]
Somebody bought my old domain and I totally forgot about that link.

Thanks for the tip.

**Comment by drhelius** [comment]
Fixed!
